# Generated by Django 4.0 on 2022-01-19 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('public_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fcm_id', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge', models.BigAutoField(primary_key=True, serialize=False)),
                ('valid', models.BooleanField(default=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.user')),
            ],
        ),
    ]
