# Generated by Django 4.0.3 on 2022-04-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
