# Generated by Django 4.0.5 on 2022-06-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
