# Generated by Django 4.0.4 on 2022-06-15 06:20

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0003_auto_20220614_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(_('email'), blank=True, unique=True, null=True),
        ),
    ]
