# Generated by Django 4.0.3 on 2022-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0004_alter_friend_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='last_sent_message_read',
        ),
        migrations.AddField(
            model_name='friend',
            name='last_sent_message_status',
            field=models.CharField(choices=[('r', 'Read'), ('d', 'Delivered'), ('s', 'Sent')], default=None, max_length=1, null=True),
        ),
    ]
