# Generated by Django 5.1 on 2024-09-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0008_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
